### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by nlebellier** [TedGoas/Dante#137]
Hello,
Thanks for sharing this repo.
But i met an issue.

```
nlb@speedy:~/Dante$ npm -v
7.19.1
nlb@speedy:~/Dante$ npm install
npm WARN EBADENGINE Unsupported engine { package: 'tailwindcss@2.2.4',
npm WARN EBADENGINE   required: { node: '>=12.13.0' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.1' } }
npm WARN EBADENGINE Unsupported engine { package: 'fs-extra@10.0.0',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.1' } }

up to date, audited 533 packages in 2s

51 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
nlb@speedy:~/Dante$ npm start

> tedgoas@1.0.0 start
> npm run clean && run-p eleventy:serve postcss:watch


> tedgoas@1.0.0 clean
> rimraf dist


> tedgoas@1.0.0 eleventy:serve
> cross-env NODE_ENV=development eleventy --serve


> tedgoas@1.0.0 postcss:watch
> postcss src/assets/css/styles.css -o dist/assets/css/styles.css --watch

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/home/nlb/Dante/node_modules/tailwindcss/lib/jit/corePlugins.js:242:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/nlb/Dante/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:36:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
ERROR: "postcss:watch" exited with 1.
```
Any idea ?
Cheers

**Comment by TedGoas** [comment]
Looks like you need to update your version of node:

```
npm WARN EBADENGINE   required: { node: '>=12.13.0' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.19.1' } }
```

**Comment by nlebellier** [comment]
hi,
Yep ! tailwindcss needs node > 12

**Comment by nlebellier** [comment]
Hi 
Just to warn you there is a wrong link from your bio page which should bring us to your email system :-)
Thanks again for sharing the sources 
Cheers
